version: 2
jobs:
  build:
    steps:
       - checkout
       - run:
          name: cx
          command: nim c -r cx.nim
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
